### ISSUE TITLE
Page URL (Import Bug)

### ISSUE THREAD

**Issue by jonwinton** [clay/claycli#25]
# Importing With Scratch
<img width="768" alt="screen shot 2017-05-31 at 8 46 54 pm" src="https://cloud.githubusercontent.com/assets/4906712/26659904/6bd3ba76-4642-11e7-95c6-f02874dd6dce.png">

# Importing with Clay CLI
<img width="755" alt="screen shot 2017-05-31 at 8 47 10 pm" src="https://cloud.githubusercontent.com/assets/4906712/26659906/7391250a-4642-11e7-9d08-9fbd8f992e87.png">

# Test YAML
```
pages:
  index:
    layout: /components/two-column-layout/instances/index
    url: /
    main:
      - /components/newsfeed/instances/index
```
