### ISSUE TITLE
BUG: clay cli does not append the correct host to the `url` property

### ISSUE THREAD

**Issue by amycheng** [clay/claycli#45]
when importing the following:

```
pages:
  style:
    layout: /components/cut-layout/instances/section
    url: /style/
    head:
      - /components/clay-meta-title/instances/style
      - /components/clay-meta-description/instances/style
      - /components/meta-image/instances/wwwthecut-index
      - /components/meta-icons/instances/wwwthecut
      - /components/clay-meta-site/instances/section
      - /components/clay-meta-url/instances/style
      - /components/clay-meta-keywords/instances/style
    top:
      - /components/ad-takeover-homepage/instances/style
      - /components/global-nav/instances/social-off
    main:
      - /components/cut-section-feed/instances/style
```

`clay-cli` does not append the host to the `url` path. When you try to publish the page via Kiln, Amphora throws an error saying the url is not valid.
