### ISSUE TITLE
import _layouts and metadata

### ISSUE THREAD

**Issue by nelsonpecora** [clay/claycli#71]
* import new top-level thing called `_layouts` (handle them as a route, and as root-level bootstrap properties)
* import `meta` (handle them as a route for pages and layouts, and as properties of layouts/pages in bootstraps)

```yaml
_layouts:
  abc:
    head: []
    main: main
    instances:
      def:
        head:
          - '/_components/whatev'
        main: main
        meta:
          title: Whatever Layout

_pages:
  abc:
    main:
      - /_components/something
    meta:
      title: Whatever Page
```
